name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests ${{matrix.sdk}} on ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['stable']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/checkout@v2
      - run: dart --version
      - run: dart pub get
      - run: dart analyze --fatal-infos .
      - run: dart test
      - run: dart tool/generate_client.dart
      - run: dart tool/prepare_submit.dart
      - name: "check for uncommitted changes"
        run: git diff --exit-code
